version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
    labels: []

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
    labels: []
    versioning-strategy: increase
