name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.11

      - name: Setup Poetry
        uses: threeal/setup-poetry-action@v1.2.0

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4.2.3
        with:
          key: poetry-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          path: .venv

      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install --with dev

      - name: Generate Documentation
        run: poetry run poe docs

      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: apidocs

      - name: Deploy Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4.0.5
