name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-package:
    name: Check Package
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11

      - name: Setup Poetry
        uses: threeal/setup-poetry-action@v1.1.0

      - name: Cache Dependencies
        id: cache-deps
        uses: threeal/cache-action@v0.2.1
        with:
          key: poetry-${{ runner.os }}
          version: ${{ hashFiles('pyproject.toml') }}
          files: .venv

      - name: Install Dependencies
        if: steps.cache-deps.outputs.restored == 'false'
        run: poetry install --with dev

      - name: Check Format
        run: |
          poetry run poe format
          git diff --exit-code HEAD

      - name: Check Lint
        run: poetry run poe lint

  test-package:
    name: Test Package
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11

      - name: Setup Poetry
        uses: threeal/setup-poetry-action@v1.1.0

      - name: Cache Dependencies
        id: cache-deps
        uses: threeal/cache-action@v0.2.1
        with:
          key: poetry-${{ runner.os }}
          version: ${{ hashFiles('pyproject.toml') }}
          files: .venv

      - name: Install Dependencies
        if: steps.cache-deps.outputs.restored == 'false'
        run: poetry install --with dev

      - name: Test Package
        run: poetry run poe test
